return {

	MaxBlur = 10;
	BlurMult = 3.5;

	DriftMin = -3;
	DriftMax = 3;

	BaseMult = 12;

	BreathingScale = {X = 0; Y = 2};
	BreathingSpeed = 3;

	TiltAngle = 2.5;
	TiltSpeed = 2;
	TiltDamper = 0.8;

	LookSwayMaxAngle = {X = 8; Y = 2};
	LookSwayMouseDamper = {X = 1; Y = 12};
	LookSwaySpeed = 5;
	LookSwayDamper = 0.65;

	LandEffectVelocity = 12.5;
	LandEffectSpeed = 8;
	LandEffectDamper = 0.4;
}
